# Generated by Django 5.0 on 2023-12-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NomeViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('datainicio', models.DateField()),
                ('datafinal', models.DateField()),
                ('atividade', models.BooleanField()),
                ('idcarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.carros')),
                ('ususario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('qnt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.IntegerField()),
                ('kminicial', models.IntegerField()),
                ('kmfinal', models.IntegerField()),
                ('kmrodado', models.IntegerField()),
                ('media', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idcidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.cidades')),
                ('idnomeviagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.nomeviagem')),
                ('idpagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.pagamentos')),
                ('idtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.tipos')),
            ],
        ),
    ]
