# Generated by Django 5.0 on 2023-12-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomeviagem',
            old_name='ususario',
            new_name='usuario',
        ),
    ]
