# Generated by Django 5.0 on 2023-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0002_rename_ususario_nomeviagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='nota',
            field=models.IntegerField(unique=True),
        ),
    ]
