# Generated by Django 5.0 on 2023-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0003_alter_despesas_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomeviagem',
            name='kmfinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nomeviagem',
            name='kminicial',
            field=models.IntegerField(default=0),
        ),
    ]
