# Generated by Django 5.0 on 2023-12-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0004_nomeviagem_kmfinal_nomeviagem_kminicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='imagemnota',
            field=models.FileField(null=True, upload_to='notas'),
        ),
    ]
