# Generated by Django 5.0 on 2023-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0005_despesas_imagemnota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='imagemnota',
            field=models.FileField(default='nada', null=True, upload_to='notas'),
        ),
    ]
